boadproject/accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns =[
    path('register/', views.SignUpView.as_view(), name='register'), 
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),  name='login' ), 
    path('password/', views.B.as_view(),  name='password'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout' ), 
    path('password/done/', views.A.as_view(), name = 'password_reset_done'),
    path(r'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name='password_reset_confirm'), 
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password_done.html"), name='password_complete'), 
]

boadproject/boadapp/urls.py
from django.urls import path
from . import views

app_name = 'boadapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    path('success/', views.SuccessView.as_view(), name='index_login'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

boadproject/boadproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('boadapp.urls')), 
    path('', include('accounts.urls')), 
]

boadproject/accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    
    pass

boadproject/boadapp/models.py
from django.db import models

# Create your models here.

boadproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = \
        'user name'
        
        self.fields['username'].widget.attrs['class'] = 'form-control'
        
        self.fields['email'].widget.attrs['placeholder'] = \
        'Email adress'
        
        self.fields['email'].widget.attrs['class'] = 'form-control'
        
        self.fields['password1'].widget.attrs['placeholder'] = \
        'Password'
        
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        
        self.fields['password2'].widget.attrs['placeholder'] = \
        'Confirm Password'
        
        self.fields['password2'].widget.attrs['class'] = 'form-control'

boadproject/boadapp/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.forms.utils import ErrorList

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = \
        'お名前を入力してください'
        
        self.fields['name'].widget.attrs['class'] = 'form-control'
        
        self.fields['email'].widget.attrs['placeholder'] = \
        'メールアドレスを入力してください'
        
        self.fields['email'].widget.attrs['class'] = 'form-control'
        
        self.fields['title'].widget.attrs['placeholder'] = \
        'タイトルを入力してください'
        
        self.fields['title'].widget.attrs['class'] = 'form-control'
        
        self.fields['message'].widget.attrs['placeholder'] = \
        'メッセージを入力してください'
        
        self.fields['message'].widget.attrs['class'] = 'form-control'

boadproject/accounts/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.contrib.auth import views as auth_views

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy('accounts:login')
    
    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class A(auth_views.PasswordResetDoneView):
    template_name = 'password_reset_sent.html'
    
class B(auth_views.PasswordResetView):
    template_name='password.html'
    success_url = reverse_lazy('accounts:password_reset_done')
        

boadproject/boadapp/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import FormView
from django.urls import reverse_lazy
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage

class IndexView(TemplateView):
    template_name = 'index.html'
    

class SuccessView(TemplateView):
    template_name = 'index_login.html'
    

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('boadapp:contact')
    
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = \
            '送信者名: {0}\nメールアドレス: {1}\n タイトル: {2}\n メッセージ: \n{3}'\
            .format(name, email, title, message)
        from_email = 'majyonotabi@gmail.com'
        to_list = ['majyonotabi@gmail.com']
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list,)
        message.send()
        messages.success(self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

boadproject/accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Login - SB Admin</title>
        <link href= {% static "css/signin.css" %} rel="stylesheet">
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <main class="form-signin">
        <form method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-notmal">Please sign in</h1>

            {% if form.errors %}
            <p style="clor: red">ユーザー名とパスワードが一致しません</p>
        {% endif %}
            <label for="Username" class="visually-hidden">User name</label>
            <input type="text"
                    name="username"
                    id="id_username"
                    maxlength="150"
                    autocaptalize="none"
                    autocomplete="username"
                    class="form-control"
                    placeholder="ユーザー名"
                    required autofocus>
            <input type="password"
                    name="password"
                    id="id_password"
                    autocomplete="current-password"
                    class="form-control"
                    placeholder="パスワード"
                    required autofocus>
                    
            <input class="w-100 btn btn-lg btn-primary"
                    type="submit"
                    value="ログイン">
            <br></br>
            <p><a href="{% url 'accounts:password' %}">パスワードを忘れましたか？</a></p>
            <p><a href="{% url 'accounts:register' %}">初めての方はサインアップ</a></p>
            <input type="hidden"
                    name="next"
                    value="{% url 'boadapp:index_login' %}">
        </form>
        </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

boadproject/accounts/templates/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %}/>
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/signin.css' %} rel="stylesheet" />
    </head>
    <body>
        <body class="bg-primary">
            <div id="layoutAuthentication">
                <div id="layoutAuthentication_content">
                    <main>
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-7">
                                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                                        <form method="post">
                                        <div class="card-header"><h1 class="text-center font-weight-light my-4">Log Out</h1></div>
                                        <div class="card-body">
                                            <h1>ログアウトしました。</h1>
                                            <a class="btn btn-light btn-xl" href="{% url 'boadapp:index' %}">『Home』へ</a>
                                        </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        </html>

boadproject/accounts/templates/password.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Password Reset - SB Admin</title>
        <link href="{% static 'css/signin.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-body">
                                        <form action="" method="POST" class="text-center">
                                        {% csrf_token %}
                                            <div class="card-header"><h1 class="text-center font-weight-light my-4">Password Reset</h1></div>
                                            <div class="card-header"><h3>メールアドレスを入力してください。<br>パスワードをリセットするリンクを送信します。</h3></div>
                                            <div class="form-floating mb-3">
                                                {{ form.email }}
                                            </div>
                                                <input type="submit" value="メールを受け取る">
                                                <a class="small" href="{% url 'accounts:login' %}">ログインページへ</a>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

boadproject/accounts/templates/password_reset_done.html
hello world

boadproject/accounts/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>
<body>
    <div class="pad">
        <h2>Test Profile</h2>
        <h4>
            新しいパスワードを2回入力してください。これにより、
            正しく入力できたことが確認されます。
        </h4>
        <br />

        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="パスワードリセット"/>
        </form>
    </div>
</body>
</html>

boadproject/accounts/templates/password_reset_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %}/>
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/signin.css' %} rel="stylesheet" />
    </head>
    <body>
        <body class="bg-primary">
            <div id="layoutAuthentication">
                <div id="layoutAuthentication_content">
                    <main>
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-7">
                                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                                        <form method="post">
                                        <div class="card-header"><h1 class="text-center font-weight-light my-4">Password Reset</h1></div>
                                        <div class="card-body">
                                            <h3>パスワードのリセット手順をメールで送信しました。<br>メールはすぐに届きます。</h3>
                                            <h4>メールが届かない場合は<br>登録済みのメールアドレスであるかを確認し<br>迷惑メールフォルダーも確認してください。</h4>
                                            <a class="btn btn-light btn-xl" href="{% url 'boadapp:index' %}">『Home』へ</a>
                                        </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        </html>

boadproject/accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Register - SB Admin</title>
        <link href="{% static 'css/signin.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-7">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-body">
                                        <form method='post'>
                                            <div class="card-header"><h1 class="text-center font-weight-light my-4">Create Account</h1></div>
                                            {% csrf_token %}
                                                    {{ form.username }}
                                                    {{ form.email }}
                                                    {{ form.password1 }}
                                                    {{ form.password2 }}
                                            <input class="w-100 btn btn-lg btn-primary"
                                                    type="submit"
                                                    value="サインアップ">
                                                <p><a href="{% url 'accounts:login' %}">登録済みの方はログイン</a></p>
                                        </div>
                                                </form>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

boadproject/boadapp/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %}/>
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/app_styles.css' %} rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'boadapp:index_login' %}">Home</a>
                <button class="navbar-toggler navbar-toggler-right" 
                        type="button" 
                        data-bs-toggle="collapse" 
                        data-bs-target="#navbarResponsive" 
                        aria-controls="navbarResponsive" 
                        aria-expanded="false" 
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Log_out</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'boadapp:index_login' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'boadapp:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">『私』の趣味全開<br>自己紹介サイト<br>Contact</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">連絡を取りたい方は、以下のフォームに記入してメールを送信してください。<br>できるだけ早くご連絡します。</p>
                        <a class="btn btn-primary btn-xl" href="#form">フォームへ</a>
                    </div>
                </div>
            </div>
        </header>
        <!--contact-->
        <body>
            {% if messages %}
            <ul class="list-unstyled" style="list-style: none;">
                {% for message in messages %}
                <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <div>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-floating" id=form>
                            <div class="form-group floating-label-form-group controls">
                                {{ field.label_tag }}
                                {{ field }}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>                    
                    {% endfor %}
                    <br>
                    <button type="submit"
                            class="btn btn-primary"
                            id="sendMessageButton">Send</button>
                </form>
            </div>
        </body>
</html>

boadproject/boadapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %}/>
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/app_styles.css' %} rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">『私』の趣味全開<br>自己紹介サイト</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">一度作りましたが、今回はフレームワークを使い、そして自分の趣味全開でやっていきたいと思います。</p>
                        <a class="btn btn-primary btn-xl" href="{% url 'accounts:login' %}">ログイン</a>
                    </div>
                </div>
            </div>
        </header>
    </body>
</html>